"""empty message

Revision ID: d7de7b34e91a
Revises: 34a9d2bbb843
Create Date: 2020-03-08 23:20:50.697334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7de7b34e91a'
down_revision = '34a9d2bbb843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist_Genres', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.drop_constraint('Artist_Genres_venue_id_fkey', 'Artist_Genres', type_='foreignkey')
    op.create_foreign_key(None, 'Artist_Genres', 'Artist', ['artist_id'], ['id'])
    op.drop_column('Artist_Genres', 'venue_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist_Genres', sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Artist_Genres', type_='foreignkey')
    op.create_foreign_key('Artist_Genres_venue_id_fkey', 'Artist_Genres', 'Artist', ['venue_id'], ['id'])
    op.drop_column('Artist_Genres', 'artist_id')
    # ### end Alembic commands ###
